### ISSUE TITLE
Implement boilerplate or wrapper with common arguments, documentation format

### ISSUE THREAD

**Issue by chaomodus** [dunex-project/dunex-core#62]
I have a prototype, but I would like some opinions. I was doing some shopping and it looks like Commandr https://github.com/robik/commandr is a much nicer command-line parser which supports positional arguments (something that has bugged me about std.getopt) and more convenient validators.

It'd be nice if every command had --help, --version, listed authors, version, etc, which commandr has sort of built in which is nice, also it's more convenient from a providing-core-functionality point of view.

**Comment by Member1221** [comment]
I think we should build our own command parser that mixes commandr and some compile time metaprogramming to autogenerate the authors from an enum, etc.

**Comment by chaomodus** [comment]
Yah I agree with that, in general. I don't of course know *how* to do it, but that's what I'm desire out of it.

**Comment by Member1221** [comment]
Once I'm capable I could mock up a prototype, might take a couple of weeks, though.
Untill then let's stay with getopt then move over.

**Comment by chaomodus** [comment]
This is fixed with https://github.com/dunex-project/dunex-core/commit/7a404faa781bc90cc072e840126e8f0cd529f736#diff-6bfd1edc72b60bcda021126b03f68723
