### ISSUE TITLE
tty: Implement proper exit status

### ISSUE THREAD

**Issue by chaomodus** [dunex-project/dunex-core#79]
According to the FreeBSD manpage:

```
EXIT STATUS

     The tty utility exits 0 if the standard input is a terminal, 1 if the standard input is not a terminal, and >1 if an error occurs.
```

This is likely consistent with the GNU version also, but it is not documented that way. (This makes sense with the -s argument).

**Comment by chaomodus** [comment]
The manpage also notes that `test` is meant to be used instead of `tty` to test if a tty is connected to the process, so -s is deprecated, I make no such determination personally.

**Comment by Marie-Joseph** [comment]
This issue can probably be closed, yes?
